include $(CLEAR_VARS)
LOCAL_MODULE := GCamera
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := GCam/Gcam_6.1.021_Advanced_V1.7.190716.1800.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := Snap Camera2 Camera
include $(BUILD_PREBUILT)
